version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=film;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=hoang2k3ql1@
    depends_on:
      - sqlserver
    restart: always
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - SA_PASSWORD=hoang2k3ql1@
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr --accept-eula &
        sleep 30
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P hoang2k3ql1@ -Q "CREATE DATABASE film"
        wait
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1433" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  sqlserver-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
