import AdminApi from "@/app/api/AdminApi";
import React from "react";
const columns = [
    { name: "Tên", uid: "name", sortable: true },
    { name: "Tuổi", uid: "age", sortable: true },
    { name: "Số tiền đã nạp", uid: "totalmoney", sortable: true },
    { name: "EMAIL", uid: "email" },
    { name: "Trạng thái", uid: "status", sortable: true },
    { name: "Hành động", uid: "actions" },
];

const statusOptions = [
    { name: "Vip", uid: "vip" },
    { name: "Normal", uid: "normal" },
];
const users = async () => {
    try {
        const res = await AdminApi.GetAllUser();
        return res.data;
    } catch (err) {
        console.log(err);
        return []; // Trả về một mảng trống trong trường hợp có lỗi xảy ra
    }
}

// const users = [
//     {
//         id: 1,
//         name: "Tony Reichert",
//         totalmoney: 300000,
//         team: "Management",
//         status: "vip",
//         age: "29",
//         avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
//         email: "tony.reichert@example.com",
//     },
//     {
//         id: 2,
//         name: "Zoey Lang",
//         totalmoney: 450000,
//         team: "Development",
//         status: "normal",
//         age: "25",
//         avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
//         email: "zoey.lang@example.com",
//     },
//     {
//         id: 3,
//         name: "Jane Fisher",
//         totalmoney: 230000,
//         team: "Development",
//         status: "vip",
//         age: "22",
//         avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
//         email: "jane.fisher@example.com",
//     },
//     {
//         id: 4,
//         name: "William Howard",
//         totalmoney: 500000,
//         team: "Marketing",
//         status: "normal",
//         age: "28",
//         avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
//         email: "william.howard@example.com",
//     },
//     {
//         id: 5,
//         name: "Kristen Copper",
//         totalmoney: 1000000,
//         team: "Sales",
//         status: "vip",
//         age: "24",
//         avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
//         email: "kristen.cooper@example.com",
//     },
//     {
//         id: 6,
//         name: "Brian Kim",
//         totalmoney: 890000,
//         team: "Management",
//         age: "29",
//         avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
//         email: "brian.kim@example.com",
//         status: "vip",
//     },
//     {
//         id: 7,
//         name: "Michael Hunt",
//         totalmoney: 499000,
//         team: "Design",
//         status: "normal",
//         age: "27",
//         avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
//         email: "michael.hunt@example.com",
//     },
//     {
//         id: 8,
//         name: "Samantha Brooks",
//         totalmoney: 1576000,
//         team: "HR",
//         status: "vip",
//         age: "31",
//         avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
//         email: "samantha.brooks@example.com",
//     },
//     {
//         id: 9,
//         name: "Frank Harrison",
//         totalmoney: 229000,
//         team: "Finance",
//         status: "normal",
//         age: "33",
//         avatar: "https://i.pravatar.cc/150?img=4",
//         email: "frank.harrison@example.com",
//     },
//     {
//         id: 10,
//         name: "Emma Adams",
//         totalmoney: 480000,
//         team: "Operations",
//         status: "vip",
//         age: "35",
//         avatar: "https://i.pravatar.cc/150?img=5",
//         email: "emma.adams@example.com",
//     },
//     {
//         id: 11,
//         name: "Brandon Stevens",
//         totalmoney: 457900,
//         team: "Development",
//         status: "vip",
//         age: "22",
//         avatar: "https://i.pravatar.cc/150?img=8",
//         email: "brandon.stevens@example.com",
//     },
//     {
//         id: 12,
//         name: "Megan Richards",
//         totalmoney: 4590000,
//         team: "Product",
//         status: "normal",
//         age: "28",
//         avatar: "https://i.pravatar.cc/150?img=10",
//         email: "megan.richards@example.com",
//     },
//     {
//         id: 13,
//         name: "Oliver Scott",
//         totalmoney: 659000,
//         team: "Security",
//         status: "vip",
//         age: "37",
//         avatar: "https://i.pravatar.cc/150?img=12",
//         email: "oliver.scott@example.com",
//     },
//     {
//         id: 14,
//         name: "Grace Allen",
//         totalmoney: 5579000,
//         team: "Marketing",
//         status: "vip",
//         age: "30",
//         avatar: "https://i.pravatar.cc/150?img=16",
//         email: "grace.allen@example.com",
//     },
//     {
//         id: 15,
//         name: "Noah Carter",
//         totalmoney: 10590000,
//         team: "I. Technology",
//         status: "normal",
//         age: "31",
//         avatar: "https://i.pravatar.cc/150?img=15",
//         email: "noah.carter@example.com",
//     },
//     {
//         id: 16,
//         name: "Ava Perez",
//         totalmoney: 459000,
//         team: "Sales",
//         status: "vip",
//         age: "29",
//         avatar: "https://i.pravatar.cc/150?img=20",
//         email: "ava.perez@example.com",
//     },
//     {
//         id: 17,
//         name: "Liam Johnson",
//         totalmoney: 659000,
//         team: "Analysis",
//         status: "vip",
//         age: "28",
//         avatar: "https://i.pravatar.cc/150?img=33",
//         email: "liam.johnson@example.com",
//     },
//     {
//         id: 18,
//         name: "Sophia Taylor",
//         totalmoney: 479000,
//         team: "Testing",
//         status: "vip",
//         age: "27",
//         avatar: "https://i.pravatar.cc/150?img=29",
//         email: "sophia.taylor@example.com",
//     },
//     {
//         id: 19,
//         name: "Lucas Harris",
//         totalmoney: 569000,
//         team: "Information Technology",
//         status: "normal",
//         age: "32",
//         avatar: "https://i.pravatar.cc/150?img=50",
//         email: "lucas.harris@example.com",
//     },
//     {
//         id: 20,
//         name: "Mia Robinson",
//         totalmoney: 800000,
//         team: "Operations",
//         status: "vip",
//         age: "26",
//         avatar: "https://i.pravatar.cc/150?img=45",
//         email: "mia.robinson@example.com",
//     },
// ];

export { columns, users, statusOptions };