import React from "react";
const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "Tên", uid: "name", sortable: true },
    { name: "Số tập", uid: "episode", sortable: true },
    { name: "Số lượt xem", uid: "watch", sortable: true },
    { name: "Trạng thái", uid: "status", sortable: true },
    { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
    { name: "Đang ra", uid: "active" },
    { name: "Tạm dừng", uid: "paused" },
    { name: "Kết thúc", uid: "end" },
];

let user = [
    {
        id: 1,
        name: "Tony Reichert",
        watch: 25600,
        team: "Manepisodement",
        status: "active",
        episode: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        type: "tony.reichert",
    },
    {
        id: 2,
        name: "Zoey Lang",
        watch: 12000,
        team: "Development",
        status: "paused",
        episode: "25",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        type: "zoey.lang",
    },
    {
        id: 3,
        name: "Jane Fisher",
        watch: 23801,
        team: "Development",
        status: "active",
        episode: "22",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        type: "jane.fisher",
    },
    {
        id: 4,
        name: "William Howard",
        watch: 20015,
        team: "Marketing",
        status: "end",
        episode: "28",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        type: "william.howard",
    },
    {
        id: 5,
        name: "Kristen Copper",
        watch: 2000,
        team: "Sales",
        status: "active",
        episode: "24",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
        type: "kristen.cooper",
    },
    {
        id: 6,
        name: "Brian Kim",
        watch: 32212,
        team: "Manepisodement",
        episode: "29",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        type: "brian.kim",
        status: "active",
    },
    {
        id: 7,
        name: "Michael Hunt",
        watch: 45650,
        team: "Design",
        status: "paused",
        episode: "27",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
        type: "michael.hunt",
    },
    {
        id: 8,
        name: "Samantha Brooks",
        watch: 11213,
        team: "HR",
        status: "active",
        episode: "31",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
        type: "samantha.brooks",
    },
    {
        id: 9,
        name: "Frank Harrison",
        watch: 774,
        team: "Finance",
        status: "end",
        episode: "33",
        avatar: "https://i.pravatar.cc/150?img=4",
        type: "frank.harrison",
    },
    {
        id: 10,
        name: "Emma Adams",
        watch: 900,
        team: "Operations",
        status: "active",
        episode: "35",
        avatar: "https://i.pravatar.cc/150?img=5",
        type: "emma.adams",
    },
    {
        id: 11,
        name: "Brandon Stevens",
        watch: 2131,
        team: "Development",
        status: "active",
        episode: "22",
        avatar: "https://i.pravatar.cc/150?img=8",
        type: "brandon.stevens",
    },
    {
        id: 12,
        name: "Megan Richards",
        watch: 987,
        team: "Product",
        status: "paused",
        episode: "28",
        avatar: "https://i.pravatar.cc/150?img=10",
        type: "megan.richards",
    },
    {
        id: 13,
        name: "Oliver Scott",
        watch: 123456,
        team: "Security",
        status: "active",
        episode: "37",
        avatar: "https://i.pravatar.cc/150?img=12",
        type: "oliver.scott",
    },
    {
        id: 14,
        name: "Grace Allen",
        watch: 8787,
        team: "Marketing",
        status: "active",
        episode: "30",
        avatar: "https://i.pravatar.cc/150?img=16",
        type: "grace.allen",
    },
    {
        id: 15,
        name: "Noah Carter",
        watch: 1230,
        team: "I. Technology",
        status: "paused",
        episode: "31",
        avatar: "https://i.pravatar.cc/150?img=15",
        type: "noah.carter",
    },
    {
        id: 16,
        name: "Ava Perez",
        watch: 11,
        team: "Sales",
        status: "active",
        episode: "29",
        avatar: "https://i.pravatar.cc/150?img=20",
        type: "ava.perez",
    },
    {
        id: 17,
        name: "Liam Johnson",
        watch: 54,
        team: "Analysis",
        status: "active",
        episode: "28",
        avatar: "https://i.pravatar.cc/150?img=33",
        type: "liam.johnson",
    },
    {
        id: 18,
        name: "Sophia Taylor",
        watch: 451,
        team: "Testing",
        status: "active",
        episode: "27",
        avatar: "https://i.pravatar.cc/150?img=29",
        type: "sophia.taylor",
    },
    {
        id: 19,
        name: "Lucas Harris",
        watch: 10023,
        team: "Information Technology",
        status: "paused",
        episode: "32",
        avatar: "https://i.pravatar.cc/150?img=50",
        type: "lucas.harris",
    },
    {
        id: 20,
        name: "Mia Robinson",
        watch: 3025,
        team: "Operations",
        status: "active",
        episode: "26",
        avatar: "https://i.pravatar.cc/150?img=45",
        type: "mia.robinson",
    },
];

export { columns, user, statusOptions };