import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/component/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className=" dark:bg-black bg-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
